### ISSUE TITLE
add tail function

### ISSUE THREAD

**Issue by shevv920** [AllDayAlone/summer#15]
`tail` receives array as the argument and returns everything from array but first element
```Javascript
const arr = [1, 2, 3, 4, 5];
const result = tail(arr);
// result: [2, 3, 4, 5]
```

**Comment by PogudoTanya** [comment]
я беру это

**Comment by PogudoTanya** [comment]
const arr = [1, 2, 3, 4, 5];
let mass;
tail=(arr)=>{
arr.shift()
return arr
}
const result = tail(arr);
console.log(result)
