### ISSUE TITLE
Make a function that finds a median of array with numbers

### ISSUE THREAD

**Issue by AllDayAlone** [AllDayAlone/summer#34]
```
median([5, 9, 6, 1, 3]) === 5
```
https://ru.wikipedia.org/wiki/%D0%9C%D0%B5%D0%B4%D0%B8%D0%B0%D0%BD%D0%B0_(%D1%81%D1%82%D0%B0%D1%82%D0%B8%D1%81%D1%82%D0%B8%D0%BA%D0%B0)

**Comment by AlekseyGoremykin** [comment]
beru
